// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionPOM.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Empleados")]
    public partial class EmpleadosFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Empleados", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "Empleados.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
#line hidden
#line 5
  await testRunner.GivenAsync("el usuario ingresa al ambiente \'http://localhost:31096/\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \'admin@plazafer.com\' y contraseña \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
  await testRunner.AndAsync("accede al módulo \'Empleado\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
  await testRunner.AndAsync("accede al submódulo \'Ver\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cambiar el estado Civil de los empleados - Casos 1 al 2")]
        [NUnit.Framework.CategoryAttribute("CambiarEstadoCivilEmpleado")]
        [NUnit.Framework.TestCaseAttribute("No especificado", "Soltero(a)", null)]
        [NUnit.Framework.TestCaseAttribute("No especificado", "Casado(a)", null)]
        [NUnit.Framework.TestCaseAttribute("No especificado", "Divorciado(a)", null)]
        [NUnit.Framework.TestCaseAttribute("No especificado", "Viudo(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Soltero(a)", "Casado(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Soltero(a)", "Divorciado(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Soltero(a)", "Viudo(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Soltero(a)", "No especificado", null)]
        [NUnit.Framework.TestCaseAttribute("Casado(a)", "Divorciado(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Casado(a)", "Viudo(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Casado(a)", "Soltero(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Casado(a)", "No especificado", null)]
        [NUnit.Framework.TestCaseAttribute("Divorciado(a)", "Casado(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Divorciado(a)", "Viudo(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Divorciado(a)", "Soltero(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Divorciado(a)", "No especificado", null)]
        [NUnit.Framework.TestCaseAttribute("Viudo(a)", "Casado(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Viudo(a)", "Divorciado(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Viudo(a)", "Soltero(a)", null)]
        [NUnit.Framework.TestCaseAttribute("Viudo(a)", "No especificado", null)]
        public async System.Threading.Tasks.Task CambiarElEstadoCivilDeLosEmpleados_Casos1Al2(string estadoInicial, string estadoFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CambiarEstadoCivilEmpleado"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("EstadoInicial", estadoInicial);
            argumentsOfScenario.Add("EstadoFinal", estadoFinal);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cambiar el estado Civil de los empleados - Casos 1 al 2", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
#line 12
 await testRunner.WhenAsync("Seleccion un empleado a editar", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
 await testRunner.AndAsync(string.Format("Cambiar el estado civil a \'{0}\'", estadoInicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
 await testRunner.AndAsync("Guardar estado civil", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.AndAsync("Editar el mismo empleado", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
 await testRunner.AndAsync(string.Format("Volve Cambiar el estado civil a \'{0}\'", estadoFinal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.ThenAsync("Volvel a Guardar estado civil", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
