// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionPOM.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("VentaPorContingencia")]
    public partial class VentaPorContingenciaFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "VentaPorContingencia", "  Como usuario del sistema\r\n  Quiero registrar ventas por contingencia\r\n  Para as" +
                "egurar la emisión correcta de comprobantes en modo contingencia", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "VenPorCont.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
#line hidden
#line 8
  await testRunner.GivenAsync("el usuario ingresa al ambiente \'http://localhost:31096/\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \'admin@plazafer.com\' y contraseña \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
  await testRunner.AndAsync("accede al módulo \'Venta\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
  await testRunner.AndAsync("accede al submódulo \'Venta por Contingencia\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro de venta por contingencia - Casos 1 al 20")]
        [NUnit.Framework.CategoryAttribute("RegistrarVentaPorContingencia")]
        [NUnit.Framework.TestCaseAttribute("1", "88008-1", "10", "1", "1", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("2", "0", "10", "1", "1", "Boleta de venta electrónica", "76018810", "0", "0", "30/10/2025", "0", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("3", "88008-1", "0", "1", "1", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("4", "0", "0", "1", "1", "Boleta de venta electrónica", "76018810", "0", "0", "0", "0", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("5", "88008-1", "10", "0", "1", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "0", "inmediata", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("6", "0", "10", "0", "1", "Boleta de venta electrónica", "76018810", "0", "0", "0", "0", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("7", "88008-1", "0", "0", "1", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "0", "inmediata", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("8", "0", "0", "0", "1", "Boleta de venta electrónica", "76018810", "0", "0", "30/10/2025", "0", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("9", "88008-1", "10", "1", "0", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("10", "0", "10", "1", "0", "Boleta de venta electrónica", "76018810", "0", "0", "30/10/2025", "0", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("11", "88008-1", "0", "1", "0", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "0", "inmediata", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("12", "0", "0", "1", "0", "Boleta de venta electrónica", "76018810", "0", "0", "0", "0", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("13", "88008-1", "10", "0", "0", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "0", "inmediata", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("14", "0", "10", "0", "0", "Boleta de venta electrónica", "76018810", "0", "0", "0", "0", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("15", "88008-1", "0", "0", "0", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("16", "0", "0", "0", "0", "Boleta de venta electrónica", "76018810", "0", "0", "30/10/2025", "0", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("17", "88008-1", "10", "1", "1", "0", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("18", "0", "10", "1", "1", "0", "76018810", "0", "0", "0", "0", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("19", "88008-1", "0", "1", "1", "0", "76018810", "0", "Ninguno", "0", "inmediata", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("20", "0", "0", "1", "1", "0", "76018810", "0", "0", "0", "0", "la venta se genera correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("21", "88008-1", "10", "0", "1", "0", "76018810", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("22", "0", "10", "0", "1", "0", "76018810", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("23", "88008-1", "0", "0", "1", "0", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("24", "0", "0", "0", "1", "0", "76018810", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("25", "88008-1", "10", "1", "0", "0", "76018810", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("26", "0", "10", "1", "0", "0", "76018810", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("27", "88008-1", "0", "1", "0", "0", "76018810", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("28", "0", "0", "1", "0", "0", "76018810", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("29", "88008-1", "10", "0", "0", "0", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("30", "0", "10", "0", "0", "0", "76018810", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("31", "88008-1", "0", "0", "0", "0", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("32", "0", "0", "0", "0", "0", "76018810", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("33", "88008-1", "10", "1", "1", "Boleta de venta electrónica", "0", "20172356720", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("34", "0", "10", "1", "1", "Boleta de venta electrónica", "0", "20172356720", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("35", "88008-1", "0", "1", "1", "Boleta de venta electrónica", "0", "20172356720", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("36", "0", "0", "1", "1", "Boleta de venta electrónica", "0", "20172356720", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("37", "88008-1", "10", "0", "1", "Boleta de venta electrónica", "0", "20172356720", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("38", "0", "10", "0", "1", "Boleta de venta electrónica", "0", "20172356720", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("39", "88008-1", "0", "0", "1", "Boleta de venta electrónica", "0", "20172356720", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("40", "0", "0", "0", "1", "Boleta de venta electrónica", "0", "20172356720", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("41", "88008-1", "10", "1", "0", "Boleta de venta electrónica", "0", "20172356720", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("42", "0", "10", "1", "0", "Boleta de venta electrónica", "0", "20172356720", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("43", "88008-1", "0", "1", "0", "Boleta de venta electrónica", "0", "20172356720", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("44", "0", "0", "1", "0", "Boleta de venta electrónica", "0", "20172356720", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("45", "88008-1", "10", "0", "0", "Boleta de venta electrónica", "0", "20172356720", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("46", "0", "10", "0", "0", "Boleta de venta electrónica", "0", "20172356720", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("47", "88008-1", "0", "0", "0", "Boleta de venta electrónica", "0", "20172356720", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("48", "0", "0", "0", "0", "Boleta de venta electrónica", "0", "20172356720", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("49", "88008-1", "10", "1", "1", "0", "0", "20172356720", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("50", "0", "10", "1", "1", "0", "0", "20172356720", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("51", "88008-1", "0", "1", "1", "0", "0", "20172356720", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("52", "0", "0", "1", "1", "0", "0", "20172356720", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("53", "88008-1", "10", "0", "1", "0", "0", "20172356720", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("54", "0", "10", "0", "1", "0", "0", "20172356720", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("55", "88008-1", "0", "0", "1", "0", "0", "20172356720", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("56", "0", "0", "0", "1", "0", "0", "20172356720", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("57", "88008-1", "10", "1", "0", "0", "0", "20172356720", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("58", "0", "10", "1", "0", "0", "0", "20172356720", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("59", "88008-1", "0", "1", "0", "0", "0", "20172356720", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("60", "0", "0", "1", "0", "0", "0", "20172356720", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("61", "88008-1", "10", "0", "0", "0", "0", "20172356720", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("62", "0", "10", "0", "0", "0", "0", "20172356720", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("63", "88008-1", "0", "0", "0", "0", "0", "20172356720", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("64", "0", "0", "0", "0", "0", "0", "20172356720", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("65", "88008-1", "10", "1", "1", "Boleta de venta electrónica", "0", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("66", "0", "10", "1", "1", "Boleta de venta electrónica", "0", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("67", "88008-1", "0", "1", "1", "Boleta de venta electrónica", "0", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("68", "0", "0", "1", "1", "Boleta de venta electrónica", "0", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("69", "88008-1", "10", "0", "1", "Boleta de venta electrónica", "0", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("70", "0", "10", "0", "1", "Boleta de venta electrónica", "0", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("71", "88008-1", "0", "0", "1", "Boleta de venta electrónica", "0", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("72", "0", "0", "0", "1", "Boleta de venta electrónica", "0", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("73", "88008-1", "10", "1", "0", "Boleta de venta electrónica", "0", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("74", "0", "10", "1", "0", "Boleta de venta electrónica", "0", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("75", "88008-1", "0", "1", "0", "Boleta de venta electrónica", "0", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("76", "0", "0", "1", "0", "Boleta de venta electrónica", "0", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("77", "88008-1", "10", "0", "0", "Boleta de venta electrónica", "0", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("78", "0", "10", "0", "0", "Boleta de venta electrónica", "0", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("79", "88008-1", "0", "0", "0", "Boleta de venta electrónica", "0", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("80", "0", "0", "0", "0", "Boleta de venta electrónica", "0", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("81", "88008-1", "10", "1", "1", "0", "0", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("82", "0", "10", "1", "1", "0", "0", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("83", "88008-1", "0", "1", "1", "0", "0", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("84", "0", "0", "1", "1", "0", "0", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("85", "88008-1", "10", "0", "1", "0", "0", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("86", "0", "10", "0", "1", "0", "0", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("87", "88008-1", "0", "0", "1", "0", "0", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("88", "0", "0", "0", "1", "0", "0", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("89", "88008-1", "10", "1", "0", "0", "0", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("90", "0", "10", "1", "0", "0", "0", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("91", "88008-1", "0", "1", "0", "0", "0", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("92", "0", "0", "1", "0", "0", "0", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("93", "88008-1", "10", "0", "0", "0", "0", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("94", "0", "10", "0", "0", "0", "0", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("95", "88008-1", "0", "0", "0", "0", "0", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("96", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("97", "88008-1", "10", "1", "1", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("98", "0", "10", "1", "1", "Boleta de venta electrónica", "76018810", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("99", "88008-1", "0", "1", "1", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("100", "0", "0", "1", "1", "Boleta de venta electrónica", "76018810", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("101", "88008-1", "10", "0", "1", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("102", "0", "10", "0", "1", "Boleta de venta electrónica", "76018810", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("103", "88008-1", "0", "0", "1", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("104", "0", "0", "0", "1", "Boleta de venta electrónica", "76018810", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("105", "88008-1", "10", "1", "0", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("106", "0", "10", "1", "0", "Boleta de venta electrónica", "76018810", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("107", "88008-1", "0", "1", "0", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("108", "0", "0", "1", "0", "Boleta de venta electrónica", "76018810", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("109", "88008-1", "10", "0", "0", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("110", "0", "10", "0", "0", "Boleta de venta electrónica", "76018810", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("111", "88008-1", "0", "0", "0", "Boleta de venta electrónica", "76018810", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("112", "0", "0", "0", "0", "Boleta de venta electrónica", "76018810", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("113", "88008-1", "10", "1", "1", "0", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("114", "0", "10", "1", "1", "0", "76018810", "0", "0", "30/10/2025", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("115", "88008-1", "0", "1", "1", "0", "76018810", "0", "Ninguno", "30/10/2025", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("116", "0", "0", "1", "1", "0", "76018810", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("117", "88008-1", "10", "0", "1", "0", "76018810", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("118", "0", "10", "0", "1", "0", "76018810", "0", "0", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("119", "88008-1", "0", "0", "1", "0", "76018810", "0", "Ninguno", "0", "inmediata", "0", null)]
        [NUnit.Framework.TestCaseAttribute("120", "0", "0", "0", "1", "0", "76018810", "0", "0", "30/10/2025", "0", "0", null)]
        public async System.Threading.Tasks.Task RegistroDeVentaPorContingencia_Casos1Al20(string caso, string producto, string cantidad, string igv, string detalle, string documento, string dni, string ruc, string observacion, string emision, string entrega, string resultado, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RegistrarVentaPorContingencia"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("caso", caso);
            argumentsOfScenario.Add("producto", producto);
            argumentsOfScenario.Add("cantidad", cantidad);
            argumentsOfScenario.Add("igv", igv);
            argumentsOfScenario.Add("detalle", detalle);
            argumentsOfScenario.Add("documento", documento);
            argumentsOfScenario.Add("dni", dni);
            argumentsOfScenario.Add("ruc", ruc);
            argumentsOfScenario.Add("observacion", observacion);
            argumentsOfScenario.Add("emision", emision);
            argumentsOfScenario.Add("entrega", entrega);
            argumentsOfScenario.Add("resultado", resultado);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro de venta por contingencia - Casos 1 al 20", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 15
  await testRunner.WhenAsync(string.Format("el usuario selecciona el producto \'{0}\'", producto), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
  await testRunner.AndAsync(string.Format("define la cantidad \'{0}\'", cantidad), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
  await testRunner.AndAsync(string.Format("define IGV \'{0}\'", igv), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
  await testRunner.AndAsync(string.Format("define detalle unificado \'{0}\'", detalle), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
  await testRunner.AndAsync(string.Format("selecciona el documento \'{0}\'", documento), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
  await testRunner.AndAsync(string.Format("ingresa el DNI \'{0}\'", dni), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
  await testRunner.AndAsync(string.Format("ingresa el RUC \'{0}\'", ruc), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
  await testRunner.AndAsync(string.Format("escribe observación \'{0}\'", observacion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
  await testRunner.AndAsync(string.Format("define la fecha de emisión \'{0}\'", emision), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
  await testRunner.AndAsync(string.Format("define la entrega \'{0}\'", entrega), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
  await testRunner.ThenAsync("la venta se genera correctamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
